openapi: 3.0.0
info:
  title: API de Ejemplo
  description: API de ejemplo para Lambda y SQS
  version: 1.0.0
servers:
  - url: http://localhost:4566/restapis/{restapi_id}/_user_request_
    variables:
      restapi_id:
        default: 'YOUR_REST_API_ID'
paths:
  /send-message:
    post:
      summary: Envía un mensaje a la cola SQS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Mensaje enviado
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  body:
                    type: string
                  sqs_response:
                    type: object