server:
  port: ${PORT:8089}
    
spring:
  cloud:
    aws:
      region:
        static: ${DEFAULT_REGION:us-east-1}  # La región que uses en LocalStack
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID:test}  # Valores ficticios, LocalStack no valida esto
        secretKey: ${AWS_SECRET_ACCESS_KEY:test}
  profiles:
    active: ${PROFILE_ACTIVE:localstack} # o 'aws' dependiendo del entorno      
        
#Configuración de AWS y nombre de la cola
custom:
  aws:
    sqsOrders: ${SQS_ORDERS:message-to-sqs.fifo}
    
logging:
  level:
    root: info